---
- name: deploy
  hosts: deploy
  roles:
     - role: preconfig
       tags: preconfig
     - role: deploy
       tags: deploy
     - role: build
       tags: build

- name: managers
  hosts: managers
  roles:
     - role: preconfig
       tags: preconfig

- name: workers
  hosts: workers
  roles:
     - role: preconfig
       tags: preconfig
