galaxy_info:
  role_name: swarm_join
  description: Подключение к кластеру
  author: Vadim Vadimov
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
