galaxy_info:
  role_name: preconfig
  description: Настройка сервера для Docker
  author: Vadim Vadimov
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
