---
- name: "[{{ name }}] конфигурация secret"
  block:
    - name: "[{{ name }}] cоздаем secret"
      include: "secret-create.yml"
  tags: "{{ name }}"
  rescue:
    - name: "[{{ name }}] удаляем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "[{{ name }}] переcоздаем secret"
      include: "secret-create.yml"
