---
- name: Установка Docker
  block:
    - name: Добавляем UNIVERSE
      apt_repository:
        repo: "deb http://ru.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Установка доп. пакетов
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        update_cache: true
        cache_valid_time: 86400

    - name: Добавление ключа Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: Добавляем стабильный репо
      apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update-cache: true
        filename: docker

    - name: Установка docker-ce и проверка установки.
      apt:
        name: "{{ packages }}"
        state: present
        update-cache: true
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - docker status
  become: true

- name: Установка Docker-compose
  block:
    - name: Получение версии Docker-compose
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        body_format: json
      register: page
    - name: Установка  Docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 0755
  become: true

- name: Настройка доп.пакетов python
  block:
    - name: pip пакеты
      pip:
        name: docker

- name: Завершение установки.
  block:
    - name: Добавление пользователя
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
    - name: Перезагрузка
      reboot:

  become: true
